### ISSUE TITLE
Running generator throws "Error: More than one instance of bitcore-lib found"

### ISSUE THREAD

**Issue by kossmoboleat** [evannetwork/generator-evan#1]
I've installed `generator-evan` using NPM 6.4.1 on a 10.15.3 node setup. This is on macOs 10.14.4.

The installation succeeds after a long time, but running `yo evan` throws an error:

```
~/P/c/d/c/workshop-hem » npm install -g generator-evan
[..]
urself.
npm WARN bitcore-mnemonic@1.7.0 requires a peer of bitcore-lib@^0.16.0 but none is installed. You must install peer dependencies yourself.

+ generator-evan@1.9.3
added 890 packages from 664 contributors in 475.536s
~/P/c/d/c/workshop-hem » yo evan
/Users/tim/.asdf/installs/nodejs/10.15.3/.npm/lib/node_modules/generator-evan/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/Users/tim/.asdf/installs/nodejs/10.15.3/.npm/lib/node_modules/generator-evan/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/Users/tim/.asdf/installs/nodejs/10.15.3/.npm/lib/node_modules/generator-evan/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/tim/.asdf/installs/nodejs/10.15.3/.npm/lib/node_modules/generator-evan/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/tim/.asdf/installs/nodejs/10.15.3/.npm/lib/node_modules/generator-evan/node_modules/bitcore-mnemonic/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

**Comment by Tschuck** [comment]
Problem is solved with the following post by disabling _bitcore getter: https://github.com/bitpay/bitcore/issues/1457#issuecomment-467594031

Is released in version v1.9.4: https://github.com/evannetwork/generator-evan/releases/tag/v1.9.4
